branches:
  except:
  - l10n_master

os:
  - linux
  - osx

sudo: false

dist: bionic

addons:
  apt:
    packages:
      - rpm

git:
  depth: 5

language: node_js

node_js:
  - 10

addons:
  chrome: stable

before_install:
  - |
    echo "Target branch: $TRAVIS_BRANCH"
    echo "Commit range: $TRAVIS_COMMIT_RANGE"
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      COMMIT_RANGE="$TRAVIS_BRANCH"
    else
      COMMIT_RANGE="$TRAVIS_COMMIT_RANGE"
    fi
    git diff --name-only $COMMIT_RANGE | grep -qvE '(\.md)|(^(locales|resources/osd))/' || {
      echo "Only files not used in the build process were updated, aborting."
      exit
    }

script:
  - yarn test
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn gulp release --chromeos; fi

cache:
  directories:
  - node_modules