os:
  - linux
  - osx

sudo: false

dist: bionic

addons:
  apt:
    packages:
      - rpm

git:
  depth: 5

language: node_js

node_js:
  - 10

addons:
  chrome: stable

script:
  - yarn test
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn gulp release --chromeos; fi

cache:
  directories:
  - node_modules